# not actually YAML but lets pretend:
# -*- mode: yaml -*-
# vim: ft=yaml:
#

# Parses users.conf configuration first
% users.conf

[global]
# NETWORKING
  p: 80, 443, 3923                   # HTTP, HTTPs, default copyparty port

  z                                  # enable zerconf
  z-on: 192.168.0.0/16, 10.0.0.0/24  # restrict mdns and ssdp to local subnets

  ban-404: no
  ban-403: no
  ban-422: no
  ban-url: no
  ban-pw: no

# FILESYSTEM
  e2dsa                              # index filesystem on startup
  e2ts                               # index files on upload
  re-maxage: 86400                   # rescan every 12 hours just in case



[accounts]
  admin: 1966

