# not actually YAML but lets pretend:
# -*- mode: yaml -*-
# vim: ft=yaml:

[global]
# NETWORKING
  p: 80, 443, 3923                   # HTTP, HTTPs, default copyparty port

  z                                  # enable zerconf
  z-on: 192.168.0.0/16, 10.0.0.0/24  # restrict mdns and ssdp to local subnets

# FILESYSTEM
  e2dsa                              # index filesystem on startup
  e2ts                               # index files on upload
  re-maxage: 43200                   # rescan every 12 hours just in case


# include users.conf
% users.conf
