[/]
  /mnt/{storage}
  accs:
    A: admin

[/backup]
  /mnt/{backup}
  accs:
    A: admin


[/project_files]
  /mnt/{storage}/{projectFiles}
  accs:
    A: admin
    r: @apprentices

[/misc]
  /mnt/{storage}/{misc}
  accs:
    A: admin
