[accounts]
  aubreys: aubreys
  autumnn: autumnn
  avleend: avleend
  axtons: axtons
  azarielb: azarielb
  bennettw: bennettw
  bensons: bensons
  brendha: brendha
  brightonv: brightonv


[/Aubrey S]
  ./apprentice_folders/Aubrey S
  accs:
    rw: aubreys

[/Autumn N]
  ./apprentice_folders/Autumn N
  accs:
    rw: autumnn

[/Avleen D]
  ./apprentice_folders/Avleen D
  accs:
    rw: avleend

[/Axton S]
  ./apprentice_folders/Axton S
  accs:
    rw: axtons

[/Azariel B]
  ./apprentice_folders/Azariel B
  accs:
    rw: azarielb

[/Bennett W]
  ./apprentice_folders/Bennett W
  accs:
    rw: bennettw

[/Benson S]
  ./apprentice_folders/Benson S
  accs:
    rw: bensons

[/Brendha]
  ./apprentice_folders/Brendha
  accs:
    rw: brendha

[/Brighton V]
  ./apprentice_folders/Brighton V
  accs:
    rw: brightonv

